# Include the QtPyVCP default menubar.
{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: MonoKrom Plasma
  version: v0.0.5
  author: Kurt Jacobson, James Walker
  description: >
    Plasma UI leveraging the qtpyvcp plasma processes plugin.
      * VCP Features
      * Type of machine the VCP is for
      * Development status
      * Acknowledgments

data_plugins:
    status:
      kwargs:
        cycle_time: 50
    
    persistent_data_manager:
      provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
      kwargs:
        # serialization method to use: json or pickle
        serialization_method: pickle
        # persistence_file: .vcp_data.json
    
    plasmaprocesses:
      provider: qtpyvcp.plugins.plasma_processes:PlasmaProcesses
      kwargs:
          db_type: "sqlite"
    
    file_locations:
        provider: qtpyvcp.plugins.file_locations:FileLocations
        log_level: debug
        kwargs:
          default_location: NC Files
          local_locations:
            # format: Location Name: path
            Home: ~/
            Desktop: ~/Desktop
            NC Files: ~/linuxcnc/nc_files
          #network_locations:
          #  DropBox: ~/DropBox/gcode
          
    #gcode_properties:
    #    provider: qtpyvcp.plugins.gcode_properties:GCodeProperties
        

windows:

  mainwindow:
    # Specify the class to use for the VCP's mainwindow
    #   Format: package.module:class
    provider: monokrom.plasma.mainwindow:MainWindow

    # Keyword arguments to pass when initializing the class.
    kwargs:
      # Specify the mainwindow menubar as the default.
      menu: ( default_menubar )
      # Specify the UI file to load the window layout from.
      ui_file: {{ file.dir }}/mainwindow.ui
      # Specify a stylesheet to use only for mainwindow.
      stylesheet: {{ file.dir }}/plasma.qss
      # Set the window title from from the date in the vcp section above.
      title: ( vcp.name ) ( vcp.version)

dialogs:
  open_file:
    provider: monokrom.common.widgets.input_overlay:MkInputOverlay
    kwargs:
      ui_file: {{ file.dir}}/../common/widgets/file_chooser.ui

  recent_files:
    provider: monokrom.common.widgets.input_overlay:MkInputOverlay
    kwargs:
      ui_file: {{ file.dir}}/../common/widgets/recent_file_chooser.ui

  new_process:
    #provider: monokrom.plasma.widgets.new_process:MkNewProcess
    provider: monokrom.common.widgets.input_overlay:MkInputOverlay
    kwargs:
      ui_file: {{ file.dir}}/widgets/new_process.ui
    

application:
  kwargs:
    # Specify the application wide stylesheet.
    stylesheet: {{ file.dir }}/../common/monokrom.qss
    custom_fonts: {{ file.dir }}/../common/fonts/ttf


settings:
    thc_delay:
       default_value: 0.5
       persistent: true
    
    thc_threshold:
       default_value: 1.0
       persistent: true
    
    thc_pid_p_gain:
       default_value: 10.0
       persistent: true
    
    thc_pid_i_gain:
       default_value: 0.0
       persistent: true
    
    thc_pid_d_gain:
       default_value: 0.0
       persistent: true
    
    thc_vad_threshold:
       default_value: 90
       persistent: true
    
    thc_void_override:
       default_value: 100
       persistent: true
    
    thc_safe_height:
       default_value: 5.0
       persistent: true
    
    probe_float_travel:
       default_value: 1.5
       persistent: true
    
    probe_speed:
       default_value: 300
       persistent: true
    
    probe_height:
       default_value: 25.0
       persistent: true
    
    probe_offset:
       default_value: 0.0
       persistent: true
    
    probe_ohmic_retries:
       default_value: 3
       persistent: true
    
    probe_skip_ihs:
       default_value: 0.0
       persistent: true
    
    probe_setup_speed:
       default_value: 2000
       persistent: true
    
    arc_fail_timeout:
       default_value: 3.0
       persistent: true
    
    arc_max_starts:
       default_value: 3
       persistent: true
    
    arc_retry_delay:
       default_value: 60.0
       persistent: true
    
    arc_voltage_scale:
       default_value: 1.000000
       persistent: true
    
    arc_voltage_offset:
       default_value: 0.000
       persistent: true
    
    arc_height_per_volt:
       default_value: 0.100
       persistent: true
    
    arc_ok_high_volts:
       default_value: 99999.0
       persistent: true
    
    arc_ok_low_volts:
       default_value: 60
       persistent: true
    
    scribe_arm_delay:
       default_value: 0.0
       persistent: true
    
    scribe_on_delay:
       default_value: 0.3
       persistent: true
    
    spot_threshold:
       default_value: 10
       persistent: true
    
    spot_delay:
       default_value: 0.0
       persistent: true
    
    run_save_confirm:
       default_value: false
       persistent: true
       
    run_delete_confirm:
       default_value: true
       persistent: true
    
    plasma_hole_thickness_ratio:
       default_value: 5
       persistent: true
     
    plasma_max_hole_size:
       default_value: 50.0
       persistent: true
          
    plasma_hole_detect_enable:
         default_value: true
         persistent: true
     
    plasma_arc1_percent:
         default_value: 60.0
         persistent: true
         
    plasma_arc2_percent:
         default_value: 40.0
         persistent: true
         
    plasma_arc3_percent:
         default_value: 100.0
         persistent: true
     
    plasma_leadin_percent:
         default_value: 60.0
         persistent: true
         
    plasma_arc1_distance:
         default_value: 80.0
         persistent: true

    plasma_arc2_distance:
         default_value: 20.0
         persistent: true

    plasma_arc3_distance:
         default_value: 20.0
         persistent: true

    plasma_leadin_radius:
         default_value: 3.0
         persistent: true
    
    plasma_torch_off_distance:
         default_value: 0.0
         persistent: true
         
    plasma_small_hole_detect:
        default_value: false
        persistent: true
    
    plasma_force_straight_leadin:
        default_value: false
        persistent: true
    
    plasma_small_hole_threshold:
        default_value: 3.5
        persistent: true
    
    laser_offset_x:
        default_value: 0.0
        persistent: true 

    laser_offset_y:
        default_value: 0.0
        persistent: true
        
    camera_offset_x:
        default_value: 0.0
        persistent: true 

    camera_offset_y:
        default_value: 0.0
        persistent: true 

    scribe_offset_x:
        default_value: 0.0
        persistent: true 

    scribe_offset_y:
        default_value: 0.0
        persistent: true 
    
    ohmic_offset_x:
        default_value: 0.0
        persistent: true

    ohmic_offset_y:
        default_value: 0.0
        persistent: true

    plasma_torch_pulse_sec:
        default_value: 0.3
        persistent: true
        
    ohmic_sensing_enabled:
        default_value: false
        persistent: true
    
    plasma_auto_volts:
        default_value: false
        persistent: true
        
    plasma_vad:
        default_value: false
        persistent: true
        
    plasma_void_sense:
        default_value: false
        persistent: true

    plasma_mesh_sense:
        default_value: false
        persistent: true
        
    thc_enabled:
        default_value: false
        persistent: true
        
    thc_feed_rate:
        default_value: 0.0
        persistent: true
        
    framing_feed_rate:
        default_value: 0.0
        persistent: true
    
    consumable_xy_feed_rate:
        default_value: 0.0
        persistent: true

    consumable_offset_x:
        default_value: 0.0
        persistent: true

    consumable_offset_y:
        default_value: 0.0
        persistent: true
